file_format: "1"
id: tbkblu
name: TBKblu
type: shield
url: https://github.com/manofthebees/tbkmini-zmk-config
requires: [nice_nano_v2]
features:
  -keys
siblings:
  - bumblebee_left
  - bumblebee_right