file_format: "1"
id: bumblebee
name: bumblebee
type: shield
url: https://github.com/manofthebees/bumblebee-zmk
requires: [nice_nano_v2]
features:
  -keys
siblings:
  - bumblebee_left
  - bumblebee_right